# Config for Dependabot updates. See Documentation here:
# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference

version: 2
updates:
  # Enable version updates for Python - Docker
  - package-ecosystem: docker
    directories:
      - "template/{{dkcutter.projectSlug}}/compose/local/django/"
      - "template/{{dkcutter.projectSlug}}/compose/production/django/"
    schedule:
      interval: daily
    allow:
      - dependency-name: docker.io/python
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
    commit-message:
      prefix: "chore(deps): "
    groups:
      docker-python:
        patterns:
          - docker.io/python
    labels:
      - dependencies
