[project]
name = "dkcutter-django"
version = "1.0.0"
requires-python = "==3.14.*"
classifiers = [
  "Programming Language :: Python",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.14",
]
dependencies = [
  "django-upgrade==1.32.0",
  "djlint==1.46.1",
  "jinja2==3.1.6",
  "ruff==0.16.7",
  "tox==4.61.4",
  "tox-uv==1.36.0",
]

[tool.djlint]
profile = "jinja"
include = "H017,H035"
indent = 2
max_line_length = 119
blank_line_after_tag = "load,extends"
close_void_tags = true
format_css = true
format_js = true
custom_blocks = "element,slot"
ignore_blocks = "raw"
ignore = "H006,H030,H031,T028"

[tool.djlint.css]
indent_size = 2

[tool.djlint.js]
indent_size = 2
