export const PATTERN = /\{\{(\s?dkcutter)\.(.*?)\}\}/;

export const SUPPORTED_COMBINATIONS = [
  { postgresqlVersion: "17" },
  { postgresqlVersion: "16" },
  { postgresqlVersion: "15" },
  { postgresqlVersion: "14" },
  { cloudProvider: "AWS" },
  { cloudProvider: "AWS", additionalTools: "whitenoise" },
  { cloudProvider: "GCP" },
  { cloudProvider: "GCP", additionalTools: "whitenoise" },
  {
    cloudProvider: "None",
    additionalTools: "whitenoise",
    mailService: "Mailgun",
  },
  {
    cloudProvider: "None",
    additionalTools: "whitenoise",
    mailService: "Mailjet",
  },
  {
    cloudProvider: "None",
    additionalTools: "whitenoise",
    mailService: "Mandrill",
  },
  {
    cloudProvider: "None",
    additionalTools: "whitenoise",
    mailService: "Postmark",
  },
  {
    cloudProvider: "None",
    additionalTools: "whitenoise",
    mailService: "Sendgrid",
  },
  {
    cloudProvider: "None",
    additionalTools: "whitenoise",
    mailService: "Brevo",
  },
  {
    cloudProvider: "None",
    additionalTools: "whitenoise",
    mailService: "SparkPost",
  },
  {
    cloudProvider: "None",
    additionalTools: "whitenoise",
    mailService: "Other SMTP",
  },
  { cloudProvider: "None", additionalTools: "whitenoise", mailService: "None" },
  // Note: cloudProvider=None AND useWhitenoise=false is not supported
  { cloudProvider: "AWS", mailService: "Mailgun" },
  { cloudProvider: "AWS", mailService: "Amazon SES" },
  { cloudProvider: "AWS", mailService: "Mailjet" },
  { cloudProvider: "AWS", mailService: "Mandrill" },
  { cloudProvider: "AWS", mailService: "Postmark" },
  { cloudProvider: "AWS", mailService: "Sendgrid" },
  { cloudProvider: "AWS", mailService: "Brevo" },
  { cloudProvider: "AWS", mailService: "SparkPost" },
  { cloudProvider: "AWS", mailService: "Other SMTP" },
  { cloudProvider: "AWS", mailService: "None" },
  { cloudProvider: "GCP", mailService: "Mailgun" },
  { cloudProvider: "GCP", mailService: "Mailjet" },
  { cloudProvider: "GCP", mailService: "Mandrill" },
  { cloudProvider: "GCP", mailService: "Postmark" },
  { cloudProvider: "GCP", mailService: "Sendgrid" },
  { cloudProvider: "GCP", mailService: "Brevo" },
  { cloudProvider: "GCP", mailService: "SparkPost" },
  { cloudProvider: "GCP", mailService: "Other SMTP" },
  { cloudProvider: "GCP", mailService: "None" },
  // Note: cloudProviders GCP and None
  // with mailService Amazon SES is not supported
  { frontendPipeline: "None" },
  { frontendPipeline: "Rspack" },
  { frontendPipeline: "Rspack", pkgManagerToUse: "yarn" },
  { frontendPipeline: "Rspack", pkgManagerToUse: "pnpm" },
  { frontendPipeline: "Rspack", pkgManagerToUse: "bun" },
  { frontendPipeline: "Webpack" },
  { frontendPipeline: "Webpack", pkgManagerToUse: "yarn" },
  { frontendPipeline: "Webpack", pkgManagerToUse: "pnpm" },
  { frontendPipeline: "Webpack", pkgManagerToUse: "bun" },
  { frontendPipeline: "Rspack", additionalTools: "tailwindcss" },
  { frontendPipeline: "Rspack", additionalTools: "eslint" },
  {
    frontendPipeline: "Rspack",
    additionalTools: "eslint",
    frontendPipelineLang: "ts",
  },
  { frontendPipeline: "Rspack", additionalTools: "tailwindcss,eslint" },
  { frontendPipeline: "Webpack", additionalTools: "tailwindcss" },
  {
    frontendPipeline: "Webpack",
    additionalTools: "eslint",
    frontendPipelineLang: "ts",
  },
  { frontendPipeline: "Webpack", additionalTools: "tailwindcss,eslint" },
  { additionalTools: "reactemail" },
  { additionalTools: "reactemail", pkgManagerToUse: "yarn" },
  { additionalTools: "reactemail", pkgManagerToUse: "pnpm" },
  { additionalTools: "reactemail", pkgManagerToUse: "bun" },
  { additionalTools: "reactemail,eslint" },
  { additionalTools: "reactemail,eslint", useTailwindInReactEmail: false },
  { additionalTools: "whitenoise" },
  { additionalTools: "mailpit" },
  { additionalTools: "sentry" },
  { additionalTools: "celery" },
  { restFramework: "None" },
  { restFramework: "DRF" },
  { restFramework: "DNRF" },
  { automatedDepsUpdater: "renovate" },
  { automatedDepsUpdater: "dependabot" },
];
export const UNSUPPORTED_COMBINATIONS = [
  { postgresqlVersion: 5 },
  { frontendPipeline: "Non" },
  { frontendPipeline: "Rspack", additionalTools: "tailwi" },
  { frontendPipeline: "Rspack", pkgManagerToUse: "run" },
  { additionalTools: "tailwindcss" },
  { additionalTools: "eslint" },
  { additionalTools: "tailwindcss,eslint" },
  { useTailwindInReactEmail: true },
  { restFramework: "NOn" },
  { restFramework: "Rest" },
  { cloudProvider: "None", additionalTools: "" },
  { cloudProvider: "Non" },
  { mailService: "Non" },
  { mailService: "Other" },
  { automatedDepsUpdater: "xpto" },
];
export const INVALID_SLUGS = ["", " ", "1est", "tes1@", "t!es", "project slug"];

export const EXCLUDED_DIRS = [
  "node_modules",
  ".venv",
  "venv",
  "__pycache__",
  // Package managers
  ".pnpm-store",
  ".local/state/pnpm",
  ".bun",
  ".yarn",
];
