volumes:
  {{ dkcutter.projectSlug }}_local_postgres_data: {}
  {{ dkcutter.projectSlug }}_local_postgres_data_backups: {}
  {%- if dkcutter.useCelery %}
  {{ dkcutter.projectSlug }}_local_redis_data: {}
  {%- endif %}

services:
  django:{% if dkcutter.useCelery %} &django{% endif %}
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: {{ dkcutter.projectSlug }}_local_django
    container_name: {{ dkcutter.projectSlug }}_local_django
    env_file:
      - ./.envs/.local/.postgres
      - ./.envs/.local/.django
    ports:
      - 8000:8000
    volumes:
      - /app/.venv
      - .:/app:z
    depends_on:
      - postgres
      {%- if dkcutter.useCelery %}
      - redis
      {%- endif %}
      {%- if dkcutter.useMailpit %}
      - mailpit
      {%- endif %}
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: {{ dkcutter.projectSlug }}_production_postgres
    container_name: {{ dkcutter.projectSlug }}_local_postgres
    volumes:
      - {{ dkcutter.projectSlug }}_local_postgres_data:/var/lib/postgresql/data
      - {{ dkcutter.projectSlug }}_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
  {%- if dkcutter.useMailpit %}

  mailpit:
    image: docker.io/axllent/mailpit:latest
    container_name: {{ dkcutter.projectSlug }}_local_mailpit
    ports:
      - "8025:8025"

  {%- endif %}
  {%- if dkcutter.useCelery %}

  redis:
    image: docker.io/redis:8
    container_name: {{ dkcutter.projectSlug }}_local_redis
    volumes:
      - {{ dkcutter.projectSlug }}_local_redis_data:/data

  celeryworker:
    <<: *django
    image: {{ dkcutter.projectSlug }}_local_celeryworker
    container_name: {{ dkcutter.projectSlug }}_local_celeryworker
    depends_on:
      - redis
      - postgres
      {%- if dkcutter.useMailpit %}
      - mailpit
      {%- endif %}
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: {{ dkcutter.projectSlug }}_local_celerybeat
    container_name: {{ dkcutter.projectSlug }}_local_celerybeat
    depends_on:
      - redis
      - postgres
      {%- if dkcutter.useMailpit %}
      - mailpit
      {%- endif %}
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: {{ dkcutter.projectSlug }}_local_flower
    container_name: {{ dkcutter.projectSlug }}_local_flower
    ports:
      - "5555:5555"
    command: /start-flower

  {%- endif %}
  {%- if dkcutter.frontendPipeline in ["Rspack", "Webpack"] %}

  node:
    build:
      context: .
      dockerfile: ./compose/local/node/Dockerfile
    image: {{ dkcutter.projectSlug }}_local_node
    container_name: {{ dkcutter.projectSlug }}_local_node
    depends_on:
      - django
    volumes:
      - .:/app:z
      # http://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html
      - /app/node_modules
    command: {{ dkcutter._pkgRun }} dev
    ports:
      - "3000:3000"

  {%- endif %}
  {%- if dkcutter.usePgadmin %}

  pg_admin:
    image: docker.io/dpage/pgadmin4
    container_name: {{ dkcutter.projectSlug }}_local_pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@email.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    ports:
      - 5050:80

  {%- endif %}
