{%- if dkcutter.useReactEmail %}packages:
  - emails

{% endif -%}

allowBuilds:
{%- if dkcutter.frontendPipeline == "Webpack" %}
  "@swc/core": true
{%- endif %}
{%- if dkcutter.useReactEmail %}
  esbuild: true
  sharp: true
{%- endif %}
  unrs-resolver: true
